### ISSUE TITLE
Steem and SBD price should be readable in steemit Night Mode

### ISSUE THREAD

**Issue by mightypanda-x** [stoodkev/SteemPlus#113]
#### Expected Behavior
Steem and SBD price should be readable in the Night Mode.

#### Actual Behavior
Steem and SBD price are displayed in black color in Night Mode which makes it really hard to read.

#### Steps To Reproduce
- Turn Night Mode ON for steemit.com (Its in the drop down menu when you click on the avatar).
- Click on the avatar on the top right to open the drop down menu.
- Look for the Market icon and steem/sbd price
- All items are displayed in black and very difficult to read.

#### Recording of Issue
https://youtu.be/H2ACS0E_Q-I

#### Proposed Fix
In Night mode, display text in white color.

```css
.theme-dark .DropdownMenu.show > .VerticalMenu a {
   color: #fcfcfc !important;
}
```
